-- Create social_links table
create table public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null unique,
  url text,
  icon text
);

-- Enable RLS
alter table public.social_links enable row level security;

-- Policies
create policy "Enable read access for all users" on public.social_links
  for select using (true);

create policy "Enable insert/update/delete for all users" on public.social_links
  for all using (true) with check (true);

-- Seed default rows
insert into public.social_links (platform, url, icon) values
  ('email', 'mailto:contact@umidbabayeff.com', 'FaEnvelope'),
  ('instagram', 'https://instagram.com', 'FaInstagram'),
  ('linkedin', 'https://linkedin.com', 'FaLinkedin'),
  ('youtube', 'https://youtube.com', 'FaYoutube'),
  ('tiktok', 'https://tiktok.com', 'FaTiktok')
on conflict (platform) do nothing;
