-- Create the benefits table
create table public.benefits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  icon text not null,
  language_code text not null
);

-- Enable RLS
alter table public.benefits enable row level security;

-- Create policies (Allow everyone to read, allow anon/authenticated to insert/update/delete for demo purposes)
-- In production, you'd restrict write access to authenticated admin users only.
create policy "Enable read access for all users" on public.benefits
  for select using (true);

create policy "Enable insert for all users" on public.benefits
  for insert with check (true);

create policy "Enable update for all users" on public.benefits
  for update using (true);

create policy "Enable delete for all users" on public.benefits
  for delete using (true);
